var employeeId = 1;
console.log("employeeId is type of " + typeof employeeId);
var employeeName;
employeeName = "shiva";
console.log("Employee name is of type" + employeeName);
var isEmployee = true;
console.log("isEmployee of type" + typeof isEmployee);
var nullValue = null;
console.log("nullValue of type" + typeof nullValue);
var undefinedValue = undefined;
console.log("undefined is of type:" + typeof undefinedValue);
var someValue = 1;
console.log("somevalue is of type " + typeof someValue);
someValue = "kumar";
console.log("somevalue is of type" + typeof someValue);
someValue = true;
console.log("somevalue is of type" + typeof someValue);
var randomNames = [];
randomNames = ["shiva", "kurni", "kumar"];
console.log(randomNames);
var randomValue = [];
randomValue = [1, 2, 3];
console.log(randomValue);
var mixedValues;
mixedValues = ["shiva", "kumar", 438, true];
console.log(mixedValues);
